// MediStore Pro License System v9.8.3 - Separate File - 0 innerHTML
const SUBSCRIPTION_PLANS={
  trial:{name:'7-Day Free Trial',price:0,days:7,code:'TRIAL',features:['Retail POS','100 Bills','Basic Support']},
  basic_m:{name:'Basic Monthly',price:299,days:30,code:'BASIC-M',features:['Retail POS','Unlimited Bills','Stock Mgmt','GSTR-1 CSV']},
  basic_y:{name:'Basic Yearly',price:2999,days:365,code:'BASIC-Y',save:'589 save',features:['Basic + 2 Month Free']},
  pro_m:{name:'Pro Monthly',price:499,days:30,code:'PRO-M',features:['Wholesale PTR','Scheme','Godown','Tally XML','E-Way JSON','EMI','UPI QR']},
  pro_y:{name:'Pro Yearly',price:4999,days:365,code:'PRO-Y',save:'989 save',features:['Pro + 2 Month Free']},
  enterprise_m:{name:'Enterprise Monthly',price:999,days:30,code:'ENT-M',features:['Multi-Branch','Realtime Sync','Priority Support']},
  enterprise_y:{name:'Enterprise Yearly',price:9999,days:365,code:'ENT-Y',save:'1989 save',features:['Enterprise + 2 Month Free']}
};
function generateLicenseKey(c,d){var e=Date.now()+d*86400000;var r1=Math.random().toString(36).substring(2,6).toUpperCase();var r2=Math.random().toString(36).substring(2,6).toUpperCase();return 'MEDI-'+c+'-'+r1+'-'+r2+'-'+e.toString(36).toUpperCase();}
function parseLicenseKey(k){try{var p=k.trim().toUpperCase().split('-');if(p.length<5||p[0]!='MEDI')return null;var exp=parseInt(p[p.length-1],36);if(isNaN(exp))return null;var code=p[1];var plan=null;for(var x in SUBSCRIPTION_PLANS){if(SUBSCRIPTION_PLANS[x].code===code)plan=x;}if(!plan&&code==='TRIAL')plan='trial';if(!plan)return null;return{plan:plan,expiry:exp};}catch(e){return null;}}
function getLicense(){try{return JSON.parse(localStorage.getItem('medistore_license')||'null');}catch(e){return null;}}
function saveLicense(d){localStorage.setItem('medistore_license',JSON.stringify(d));}
function isLicenseValid(){var l=getLicense();if(!l)return{valid:false,reason:'No License'};if(Date.now()>l.expiry)return{valid:false,reason:'Expired',lic:l};return{valid:true,lic:l};}
function daysLeft(ex){return Math.ceil((ex-Date.now())/86400000);}
function el(tag,style,text){var e=document.createElement(tag);if(style)e.style.cssText=style;if(text!=null)e.textContent=text;return e;}
function clearNode(n){while(n.firstChild)n.removeChild(n.firstChild);}
function renderActivationOverlay(){
  var check=isLicenseValid();var overlay=document.getElementById('license-overlay');
  if(!overlay){overlay=el('div','position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,0.85);backdrop-filter:blur(12px);display:flex;align-items:center;justify-content:center;padding:16px;overflow-y:auto;');overlay.id='license-overlay';document.body.appendChild(overlay);}
  clearNode(overlay);
  if(check.valid){overlay.style.display='none';var lic=check.lic;var dl=daysLeft(lic.expiry);var badge=document.getElementById('license-badge');if(!badge){badge=el('div','position:fixed;top:8px;right:8px;z-index:9998;background:linear-gradient(135deg,#10b981,#059669);color:white;padding:6px 12px;border-radius:20px;font-size:11px;font-weight:700;box-shadow:0 4px 12px rgba(16,185,129,0.4);display:flex;gap:6px;align-items:center;');badge.id='license-badge';document.body.appendChild(badge);}clearNode(badge);var planName=(SUBSCRIPTION_PLANS[lic.plan]&&SUBSCRIPTION_PLANS[lic.plan].name)||lic.plan;var s1=el('span',null,'\u2713 '+planName);var s2=el('span','background:rgba(0,0,0,0.2);padding:2px 6px;border-radius:10px;',dl+' din baki');var btn=el('button','margin-left:6px;background:white;color:#059669;border:none;padding:2px 6px;border-radius:10px;font-size:10px;cursor:pointer;','Manage');btn.addEventListener('click',function(){var ov=document.getElementById('license-overlay');if(ov){ov.style.display='flex';}renderActivationOverlay();});badge.appendChild(s1);badge.appendChild(s2);badge.appendChild(btn);if(dl<=3)badge.style.background='linear-gradient(135deg,#ef4444,#dc2626)';return;}
  overlay.style.display='flex';
  var card=el('div','background:white;max-width:960px;width:100%;border-radius:20px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,0.3);');
  var header=el('div','background:linear-gradient(135deg,#10b981,#059669);padding:24px;color:white;text-align:center;');
  var h1=el('h1','margin:0;font-size:26px;font-weight:900;','MediStore Pro v9.8.3 Final');var p1=el('p','margin:8px 0 0;opacity:0.9;font-size:13px;','Monthly Yearly Earning System - Pura Final');header.appendChild(h1);header.appendChild(p1);
  var body=el('div','padding:18px;');var topMsg=el('div',check.reason==='Expired'?'background:#fef2f2;border:1px solid #fecaca;color:#dc2626;padding:12px;border-radius:10px;margin-bottom:14px;text-align:center;':'background:#f0fdf4;border:1px solid #bbf7d0;color:#166534;padding:12px;border-radius:10px;margin-bottom:14px;text-align:center;');var topB=el('b',null,check.reason==='Expired'?'License Expired! Renew karo':'7 Din Free Trial - Bina card ke start karo');topMsg.appendChild(topB);body.appendChild(topMsg);
  var grid=el('div','display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin-bottom:18px;');
  Object.entries(SUBSCRIPTION_PLANS).forEach(function(entry){var k=entry[0];var p=entry[1];var isTrial=k==='trial';var box=el('div',(k==='pro_m'?'2px solid #10b981':'1px solid #e5e7eb')+';border-radius:14px;padding:14px;position:relative;background:'+(k==='pro_m'?'#f0fdf4':'white')+';');if(k==='pro_m'){var bdg=el('span','background:#10b981;color:white;padding:2px 8px;border-radius:10px;font-size:10px;position:absolute;top:-10px;left:50%;transform:translateX(-50%);','MOST POPULAR');box.appendChild(bdg);}var title=el('h3','margin:0 0 4px;font-size:15px;font-weight:800;',p.name);var price=el('div','font-size:20px;font-weight:900;color:#059669;','Rs '+p.price+(p.save?' ('+p.save+')':''));var ul=el('ul','margin:8px 0;padding-left:16px;font-size:11px;line-height:1.5;');p.features.forEach(function(f){var li=el('li',null,f);ul.appendChild(li);});var btn=el('button','width:100%;margin-top:8px;background:'+(isTrial?'#6b7280':'#10b981')+';color:white;border:none;padding:9px;border-radius:10px;font-weight:700;cursor:pointer;font-size:13px;',isTrial?'Free Trial Start':'Select');btn.addEventListener('click',function(){selectPlan(k);});box.appendChild(title);box.appendChild(price);box.appendChild(ul);box.appendChild(btn);if(!isTrial){var payBtn=el('button','width:100%;margin-top:6px;background:white;border:1px solid #10b981;color:#059669;padding:7px;border-radius:10px;font-weight:600;cursor:pointer;font-size:12px;','UPI Pay QR');payBtn.addEventListener('click',function(){payUPI(k);});box.appendChild(payBtn);}grid.appendChild(box);});body.appendChild(grid);
  var formBox=el('div','background:#f9fafb;border:1px dashed #d1d5db;border-radius:12px;padding:14px;');var formTitle=el('h4','margin:0 0 10px;font-size:14px;','License Key Hai Toh Yahan Daalo');var row1=el('div','display:flex;gap:8px;flex-wrap:wrap;');var inpShop=el('input','flex:1;min-width:140px;padding:9px;border:1px solid #d1d5db;border-radius:8px;font-size:13px;');inpShop.id='shop-name';inpShop.placeholder='Dukan naam';var inpPhone=el('input','flex:1;min-width:120px;padding:9px;border:1px solid #d1d5db;border-radius:8px;font-size:13px;');inpPhone.id='phone';inpPhone.placeholder='Mobile';row1.appendChild(inpShop);row1.appendChild(inpPhone);
  var row2=el('div','display:flex;gap:8px;margin-top:8px;');var inpKey=el('input','flex:1;padding:9px;border:1px solid #d1d5db;border-radius:8px;font-family:monospace;text-transform:uppercase;font-size:12px;');inpKey.id='license-key';inpKey.placeholder='MEDI-PRO-M-XXXX-XXXX';var actBtn=el('button','background:#111827;color:white;padding:9px 16px;border:none;border-radius:8px;font-weight:700;cursor:pointer;font-size:13px;','Activate');actBtn.addEventListener('click',activateLicense);row2.appendChild(inpKey);row2.appendChild(actBtn);
  var row3=el('div','margin-top:8px;display:flex;gap:8px;flex-wrap:wrap;');var trialBtn=el('button','background:#f3f4f6;border:1px solid #d1d5db;padding:6px 10px;border-radius:8px;font-size:11px;cursor:pointer;','Trial Generate');trialBtn.addEventListener('click',generateTrialKey);var adminBtn=el('button','background:#fef3c7;border:1px solid #fcd34d;padding:6px 10px;border-radius:8px;font-size:11px;cursor:pointer;','Admin Keys');adminBtn.addEventListener('click',openAdminPanel);row3.appendChild(trialBtn);row3.appendChild(adminBtn);
  var msgP=el('p','margin:8px 0 0;font-size:11px;');msgP.id='license-msg';formBox.appendChild(formTitle);formBox.appendChild(row1);formBox.appendChild(row2);formBox.appendChild(row3);formBox.appendChild(msgP);body.appendChild(formBox);
  card.appendChild(header);card.appendChild(body);overlay.appendChild(card);
}
function selectPlan(k){var msg=document.getElementById('license-msg');if(msg){clearNode(msg);var s=el('span','color:#059669;font-size:12px;',SUBSCRIPTION_PLANS[k].name+' select kiya - Neeche key daalo');msg.appendChild(s);}window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}
function payUPI(k){var plan=SUBSCRIPTION_PLANS[k];var UPI_ID='medistorepro@upi';var upiUrl='upi://pay?pa='+UPI_ID+'&pn=MediStore&am='+plan.price+'&cu=INR&tn='+encodeURIComponent(plan.name);var qrDiv=el('div','position:fixed;inset:0;z-index:100000;background:rgba(0,0,0,0.7);display:flex;align-items:center;justify-content:center;padding:16px;');var inner=el('div','background:white;border-radius:16px;padding:18px;max-width:340px;width:100%;text-align:center;');var h3=el('h3','margin:0;font-size:16px;',plan.name+' - Rs '+plan.price);var p=el('p','font-size:11px;color:#6b7280;margin:6px 0;','UPI App se pay karo');var box=el('div','background:#f9fafb;border-radius:10px;padding:10px;margin:10px 0;');var idDiv=el('div','font-family:monospace;font-size:13px;word-break:break-all;',UPI_ID);var amtDiv=el('div','font-size:11px;margin-top:4px;','Amount: Rs '+plan.price);box.appendChild(idDiv);box.appendChild(amtDiv);var a=el('a','display:block;background:#10b981;color:white;padding:10px;border-radius:10px;text-decoration:none;font-weight:700;margin-bottom:8px;font-size:13px;','UPI App Kholo');a.href=upiUrl;var closeBtn=el('button','width:100%;background:#f3f4f6;border:none;padding:9px;border-radius:8px;cursor:pointer;font-size:12px;','Band Karo');closeBtn.addEventListener('click',function(){qrDiv.remove();});inner.appendChild(h3);inner.appendChild(p);inner.appendChild(box);inner.appendChild(a);inner.appendChild(closeBtn);qrDiv.appendChild(inner);qrDiv.addEventListener('click',function(e){if(e.target===qrDiv)qrDiv.remove();});document.body.appendChild(qrDiv);}
function activateLicense(){var shopEl=document.getElementById('shop-name');var phoneEl=document.getElementById('phone');var keyEl=document.getElementById('license-key');var msg=document.getElementById('license-msg');var shop=shopEl?shopEl.value.trim():'';var phone=phoneEl?phoneEl.value.trim():'';var key=keyEl?keyEl.value.trim().toUpperCase():'';if(msg)clearNode(msg);if(!shop||!phone){if(msg){var s=el('span','color:#dc2626;','Dukan naam aur mobile daalo');msg.appendChild(s);}return;}if(!key){if(msg){var s=el('span','color:#dc2626;','License key daalo');msg.appendChild(s);}return;}var parsed=parseLicenseKey(key);if(!parsed){if(msg){var s=el('span','color:#dc2626;','Galat key');msg.appendChild(s);}return;}if(Date.now()>parsed.expiry){if(msg){var s=el('span','color:#dc2626;','Key expire');msg.appendChild(s);}return;}saveLicense({key:key,plan:parsed.plan,expiry:parsed.expiry,shopName:shop,phone:phone,activatedAt:Date.now()});if(msg){var s=el('span','color:#059669;','Activated! Reload ho raha...');msg.appendChild(s);}setTimeout(function(){renderActivationOverlay();location.reload();},700);}
function generateTrialKey(){var key=generateLicenseKey('TRIAL',7);var keyEl=document.getElementById('license-key');var shopEl=document.getElementById('shop-name');var phoneEl=document.getElementById('phone');var msg=document.getElementById('license-msg');if(keyEl)keyEl.value=key;if(shopEl&&!shopEl.value)shopEl.value='Demo Medical';if(phoneEl&&!phoneEl.value)phoneEl.value='9876543210';if(msg){clearNode(msg);var s=el('span','color:#059669;','Trial key: '+key+' - Activate dabao');msg.appendChild(s);}}
function openAdminPanel(){var pin=prompt('Admin PIN daalo:');if(pin!=='9999'){alert('Galat PIN - Default 9999');return;}var adminDiv=el('div','position:fixed;inset:0;z-index:100001;background:rgba(0,0,0,0.85);display:flex;align-items:center;justify-content:center;padding:16px;overflow-y:auto;');var card=el('div','background:white;border-radius:16px;max-width:680px;width:100%;padding:18px;');var h2=el('h2','margin:0 0 10px;font-size:18px;','Admin License Generator');var inpS=el('input','width:100%;padding:8px;border:1px solid #d1d5db;border-radius:8px;margin:8px 0;font-size:13px;');inpS.id='admin-shop';inpS.placeholder='Dukan naam';var gridBtns=el('div','display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:8px;margin:10px 0;');Object.entries(SUBSCRIPTION_PLANS).filter(function(e){return e[0]!=='trial';}).forEach(function(entry){var k=entry[0];var p2=entry[1];var b=el('button','padding:8px;border:1px solid #d1d5db;border-radius:10px;background:white;text-align:left;cursor:pointer;');var bb=el('b','font-size:12px;',p2.name);var pr=el('div','color:#059669;font-weight:800;font-size:13px;','Rs '+p2.price);b.appendChild(bb);b.appendChild(pr);b.addEventListener('click',function(){var shop=(document.getElementById('admin-shop')&&document.getElementById('admin-shop').value)||'Shop';var key=generateLicenseKey(p2.code,p2.days);var resultEl=document.getElementById('admin-result');if(resultEl)resultEl.textContent='KEY: '+key+' | Shop: '+shop+' | Plan: '+p2.name+' | Expiry: '+new Date(Date.now()+p2.days*86400000).toLocaleDateString('en-IN');});gridBtns.appendChild(b);});var result=el('div','margin-top:10px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:10px;padding:10px;font-family:monospace;font-size:11px;min-height:44px;word-break:break-all;');result.id='admin-result';result.textContent='Key yahan ayegi...';var closeBtn=el('button','margin-top:10px;background:#111827;color:white;padding:8px 14px;border:none;border-radius:8px;cursor:pointer;font-size:12px;','Band Karo');closeBtn.addEventListener('click',function(){adminDiv.remove();});card.appendChild(h2);card.appendChild(inpS);card.appendChild(gridBtns);card.appendChild(result);card.appendChild(closeBtn);adminDiv.appendChild(card);document.body.appendChild(adminDiv);}
document.addEventListener('DOMContentLoaded',function(){setTimeout(renderActivationOverlay,600);});
